---
collections:
  - name: ansible.posix
    version: 1.4.0
  - name: community.general
    version: 5.7.0
  - name: devsec.hardening
    version: 8.2.0

roles:
  - name: geerlingguy.docker
    version: 6.0.1
  - name: geerlingguy.ntp
    version: 2.3.1
  - name: geerlingguy.pip
    version: 2.2.0
